// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/storage/object_box/entities/cache_meta_entity.dart';
import 'features/customers/data/models/customer_entity.dart';
import 'features/hall/data/models/hall_table_entity.dart';
import 'features/items/data/models/category_entity.dart';
import 'features/items/data/models/menu_item_entity.dart';
import 'features/matches/data/models/match_seat_entity.dart';
import 'features/orders/data/models/order_entity.dart';
import 'features/orders/data/models/order_item_entity.dart';
import 'features/shift/data/models/shift_entity.dart';
import 'features/treasury/data/models/treasury_transaction_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2467054432086639830),
    name: 'CacheMetaEntity',
    lastPropertyId: const obx_int.IdUid(3, 8770416089712112328),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3196065590893594798),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1208131827266110009),
        name: 'boxName',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 8459688867663420372),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8770416089712112328),
        name: 'lastSyncedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 51273886986131299),
    name: 'HallTableEntity',
    lastPropertyId: const obx_int.IdUid(6, 7080585986145436980),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5557624914455773702),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 47306918210029795),
        name: 'number',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(2, 206817518550526951),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5506005613733163974),
        name: 'status',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4339077099392110079),
        name: 'drinkCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1319850769834674425),
        name: 'price',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7080585986145436980),
        name: 'customerName',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8036933164883014874),
    name: 'CategoryEntity',
    lastPropertyId: const obx_int.IdUid(6, 4637738635194900913),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3634287128197974807),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8491153181103086832),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6406057487100934303),
        name: 'imagePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2312335376388466502),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 161565100004498711),
        name: 'sortOrder',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4637738635194900913),
        name: 'nameEn',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 2701804075511469332),
    name: 'MenuItemEntity',
    lastPropertyId: const obx_int.IdUid(8, 5868918809248688406),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6857476281256963624),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5329367549672800137),
        name: 'categoryId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(3, 8687952214078898367),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4927379530960737911),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1830875701468274540),
        name: 'price',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3007560099142598648),
        name: 'imagePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 151867521566825830),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3383690351681681596),
        name: 'sortOrder',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5868918809248688406),
        name: 'nameEn',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 2990089501523730516),
    name: 'OrderEntity',
    lastPropertyId: const obx_int.IdUid(13, 1058970356262540544),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8156234745498481643),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2434245085690448131),
        name: 'tableId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(4, 7635035613488405237),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8851101427295631820),
        name: 'status',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1558446685199350172),
        name: 'customerName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6748057192669223055),
        name: 'paidAmount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7452196766272538600),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7935215328929589493),
        name: 'closedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4725190843476145498),
        name: 'tableNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5921008167290425336),
        name: 'paymentMethod',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4091214350343491123),
        name: 'locationKind',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 3308185234701142933),
        name: 'customerId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(8, 4871079183238634545),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4007205306913929702),
        name: 'createdBy',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 1058970356262540544),
        name: 'cancelReason',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 3149235358257446838),
    name: 'OrderItemEntity',
    lastPropertyId: const obx_int.IdUid(8, 362146733810633552),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1675749361689448928),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5020321657931603538),
        name: 'orderId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(5, 4803726187613504726),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6683874571974052516),
        name: 'menuItemId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4878921968476865844),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3213722079322121316),
        name: 'price',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8621883346423112349),
        name: 'imagePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8707967398864778225),
        name: 'quantity',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 362146733810633552),
        name: 'nameEn',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 3988311451431123324),
    name: 'TreasuryTransactionEntity',
    lastPropertyId: const obx_int.IdUid(9, 7164177762141654880),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6879485194504331333),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 339070952991510511),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3854021847752417293),
        name: 'subtitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4593289326532305552),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8392446758265605459),
        name: 'isIncome',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1630832693283340658),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4436389341659763149),
        name: 'createdBy',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 211750052639309250),
        name: 'paymentMethod',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7164177762141654880),
        name: 'orderId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(9, 125492146520739557),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 3403350787146521806),
    name: 'MatchSeatEntity',
    lastPropertyId: const obx_int.IdUid(6, 7031739963323584036),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7469679110255030775),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8122243797672262903),
        name: 'number',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(6, 5775462523835108978),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 262289914496983445),
        name: 'status',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6759726727552970288),
        name: 'drinkCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 676189158726593439),
        name: 'price',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7031739963323584036),
        name: 'customerName',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 547910549712133773),
    name: 'ShiftEntity',
    lastPropertyId: const obx_int.IdUid(6, 356420926410283648),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2124840139712219659),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1773579763143811994),
        name: 'openingBalance',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1532222920729459846),
        name: 'status',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 339181198545975529),
        name: 'startedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8772059232905414869),
        name: 'closedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 356420926410283648),
        name: 'closingBalance',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 3730376913734074424),
    name: 'CustomerEntity',
    lastPropertyId: const obx_int.IdUid(4, 7107090943000637117),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6242382197468646170),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 431151796138793526),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 888799696282343107),
        name: 'phone',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(7, 6004828314717751632),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7107090943000637117),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(10, 3730376913734074424),
    lastIndexId: const obx_int.IdUid(9, 125492146520739557),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CacheMetaEntity: obx_int.EntityDefinition<CacheMetaEntity>(
      model: _entities[0],
      toOneRelations: (CacheMetaEntity object) => [],
      toManyRelations: (CacheMetaEntity object) => {},
      getId: (CacheMetaEntity object) => object.id,
      setId: (CacheMetaEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CacheMetaEntity object, fb.Builder fbb) {
        final boxNameOffset = fbb.writeString(object.boxName);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, boxNameOffset);
        fbb.addInt64(2, object.lastSyncedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final boxNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final lastSyncedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final object = CacheMetaEntity(
          id: idParam,
          boxName: boxNameParam,
          lastSyncedAt: lastSyncedAtParam,
        );

        return object;
      },
    ),
    HallTableEntity: obx_int.EntityDefinition<HallTableEntity>(
      model: _entities[1],
      toOneRelations: (HallTableEntity object) => [],
      toManyRelations: (HallTableEntity object) => {},
      getId: (HallTableEntity object) => object.id,
      setId: (HallTableEntity object, int id) {
        object.id = id;
      },
      objectToFB: (HallTableEntity object, fb.Builder fbb) {
        final customerNameOffset = object.customerName == null
            ? null
            : fbb.writeString(object.customerName!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.number);
        fbb.addInt64(2, object.status);
        fbb.addInt64(3, object.drinkCount);
        fbb.addFloat64(4, object.price);
        fbb.addOffset(5, customerNameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final numberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final statusParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final drinkCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final priceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final customerNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = HallTableEntity(
          id: idParam,
          number: numberParam,
          status: statusParam,
          drinkCount: drinkCountParam,
          price: priceParam,
          customerName: customerNameParam,
        );

        return object;
      },
    ),
    CategoryEntity: obx_int.EntityDefinition<CategoryEntity>(
      model: _entities[2],
      toOneRelations: (CategoryEntity object) => [],
      toManyRelations: (CategoryEntity object) => {},
      getId: (CategoryEntity object) => object.id,
      setId: (CategoryEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CategoryEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final imagePathOffset = object.imagePath == null
            ? null
            : fbb.writeString(object.imagePath!);
        final nameEnOffset = object.nameEn == null
            ? null
            : fbb.writeString(object.nameEn!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, imagePathOffset);
        fbb.addInt64(3, object.createdAt?.millisecondsSinceEpoch);
        fbb.addInt64(4, object.sortOrder);
        fbb.addOffset(5, nameEnOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final createdAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameEnParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final imagePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final createdAtParam = createdAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
        final sortOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final object = CategoryEntity(
          id: idParam,
          name: nameParam,
          nameEn: nameEnParam,
          imagePath: imagePathParam,
          createdAt: createdAtParam,
          sortOrder: sortOrderParam,
        );

        return object;
      },
    ),
    MenuItemEntity: obx_int.EntityDefinition<MenuItemEntity>(
      model: _entities[3],
      toOneRelations: (MenuItemEntity object) => [],
      toManyRelations: (MenuItemEntity object) => {},
      getId: (MenuItemEntity object) => object.id,
      setId: (MenuItemEntity object, int id) {
        object.id = id;
      },
      objectToFB: (MenuItemEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final imagePathOffset = object.imagePath == null
            ? null
            : fbb.writeString(object.imagePath!);
        final nameEnOffset = object.nameEn == null
            ? null
            : fbb.writeString(object.nameEn!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.categoryId);
        fbb.addOffset(2, nameOffset);
        fbb.addFloat64(3, object.price);
        fbb.addOffset(4, imagePathOffset);
        fbb.addInt64(5, object.createdAt?.millisecondsSinceEpoch);
        fbb.addInt64(6, object.sortOrder);
        fbb.addOffset(7, nameEnOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final createdAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final categoryIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final nameEnParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final priceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final imagePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final createdAtParam = createdAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
        final sortOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = MenuItemEntity(
          id: idParam,
          categoryId: categoryIdParam,
          name: nameParam,
          nameEn: nameEnParam,
          price: priceParam,
          imagePath: imagePathParam,
          createdAt: createdAtParam,
          sortOrder: sortOrderParam,
        );

        return object;
      },
    ),
    OrderEntity: obx_int.EntityDefinition<OrderEntity>(
      model: _entities[4],
      toOneRelations: (OrderEntity object) => [],
      toManyRelations: (OrderEntity object) => {},
      getId: (OrderEntity object) => object.id,
      setId: (OrderEntity object, int id) {
        object.id = id;
      },
      objectToFB: (OrderEntity object, fb.Builder fbb) {
        final customerNameOffset = object.customerName == null
            ? null
            : fbb.writeString(object.customerName!);
        final createdByOffset = object.createdBy == null
            ? null
            : fbb.writeString(object.createdBy!);
        final cancelReasonOffset = object.cancelReason == null
            ? null
            : fbb.writeString(object.cancelReason!);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.tableId);
        fbb.addInt64(2, object.status);
        fbb.addOffset(3, customerNameOffset);
        fbb.addFloat64(4, object.paidAmount);
        fbb.addInt64(5, object.createdAt?.millisecondsSinceEpoch);
        fbb.addInt64(6, object.closedAt?.millisecondsSinceEpoch);
        fbb.addInt64(7, object.tableNumber);
        fbb.addInt64(8, object.paymentMethod);
        fbb.addInt64(9, object.locationKind);
        fbb.addInt64(10, object.customerId);
        fbb.addOffset(11, createdByOffset);
        fbb.addOffset(12, cancelReasonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final createdAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final closedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final tableIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final tableNumberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final locationKindParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final statusParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final customerIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final customerNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final paidAmountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final paymentMethodParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final createdAtParam = createdAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
        final closedAtParam = closedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(closedAtValue);
        final createdByParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final cancelReasonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final object = OrderEntity(
          id: idParam,
          tableId: tableIdParam,
          tableNumber: tableNumberParam,
          locationKind: locationKindParam,
          status: statusParam,
          customerId: customerIdParam,
          customerName: customerNameParam,
          paidAmount: paidAmountParam,
          paymentMethod: paymentMethodParam,
          createdAt: createdAtParam,
          closedAt: closedAtParam,
          createdBy: createdByParam,
          cancelReason: cancelReasonParam,
        );

        return object;
      },
    ),
    OrderItemEntity: obx_int.EntityDefinition<OrderItemEntity>(
      model: _entities[5],
      toOneRelations: (OrderItemEntity object) => [],
      toManyRelations: (OrderItemEntity object) => {},
      getId: (OrderItemEntity object) => object.id,
      setId: (OrderItemEntity object, int id) {
        object.id = id;
      },
      objectToFB: (OrderItemEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final imagePathOffset = object.imagePath == null
            ? null
            : fbb.writeString(object.imagePath!);
        final nameEnOffset = object.nameEn == null
            ? null
            : fbb.writeString(object.nameEn!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.orderId);
        fbb.addInt64(2, object.menuItemId);
        fbb.addOffset(3, nameOffset);
        fbb.addFloat64(4, object.price);
        fbb.addOffset(5, imagePathOffset);
        fbb.addInt64(6, object.quantity);
        fbb.addOffset(7, nameEnOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final orderIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final menuItemIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final nameEnParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final priceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final imagePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final quantityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = OrderItemEntity(
          id: idParam,
          orderId: orderIdParam,
          menuItemId: menuItemIdParam,
          name: nameParam,
          nameEn: nameEnParam,
          price: priceParam,
          imagePath: imagePathParam,
          quantity: quantityParam,
        );

        return object;
      },
    ),
    TreasuryTransactionEntity:
        obx_int.EntityDefinition<TreasuryTransactionEntity>(
          model: _entities[6],
          toOneRelations: (TreasuryTransactionEntity object) => [],
          toManyRelations: (TreasuryTransactionEntity object) => {},
          getId: (TreasuryTransactionEntity object) => object.id,
          setId: (TreasuryTransactionEntity object, int id) {
            object.id = id;
          },
          objectToFB: (TreasuryTransactionEntity object, fb.Builder fbb) {
            final titleOffset = fbb.writeString(object.title);
            final subtitleOffset = fbb.writeString(object.subtitle);
            final createdByOffset = object.createdBy == null
                ? null
                : fbb.writeString(object.createdBy!);
            fbb.startTable(10);
            fbb.addInt64(0, object.id);
            fbb.addOffset(1, titleOffset);
            fbb.addOffset(2, subtitleOffset);
            fbb.addFloat64(3, object.amount);
            fbb.addBool(4, object.isIncome);
            fbb.addInt64(5, object.createdAt?.millisecondsSinceEpoch);
            fbb.addOffset(6, createdByOffset);
            fbb.addInt64(7, object.paymentMethod);
            fbb.addInt64(8, object.orderId);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final createdAtValue = const fb.Int64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              14,
            );
            final idParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              4,
              0,
            );
            final titleParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 6, '');
            final subtitleParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 8, '');
            final amountParam = const fb.Float64Reader().vTableGet(
              buffer,
              rootOffset,
              10,
              0,
            );
            final isIncomeParam = const fb.BoolReader().vTableGet(
              buffer,
              rootOffset,
              12,
              false,
            );
            final paymentMethodParam = const fb.Int64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              18,
            );
            final orderIdParam = const fb.Int64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              20,
            );
            final createdAtParam = createdAtValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
            final createdByParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 16);
            final object = TreasuryTransactionEntity(
              id: idParam,
              title: titleParam,
              subtitle: subtitleParam,
              amount: amountParam,
              isIncome: isIncomeParam,
              paymentMethod: paymentMethodParam,
              orderId: orderIdParam,
              createdAt: createdAtParam,
              createdBy: createdByParam,
            );

            return object;
          },
        ),
    MatchSeatEntity: obx_int.EntityDefinition<MatchSeatEntity>(
      model: _entities[7],
      toOneRelations: (MatchSeatEntity object) => [],
      toManyRelations: (MatchSeatEntity object) => {},
      getId: (MatchSeatEntity object) => object.id,
      setId: (MatchSeatEntity object, int id) {
        object.id = id;
      },
      objectToFB: (MatchSeatEntity object, fb.Builder fbb) {
        final customerNameOffset = object.customerName == null
            ? null
            : fbb.writeString(object.customerName!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.number);
        fbb.addInt64(2, object.status);
        fbb.addInt64(3, object.drinkCount);
        fbb.addFloat64(4, object.price);
        fbb.addOffset(5, customerNameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final numberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final statusParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final drinkCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final priceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final customerNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = MatchSeatEntity(
          id: idParam,
          number: numberParam,
          status: statusParam,
          drinkCount: drinkCountParam,
          price: priceParam,
          customerName: customerNameParam,
        );

        return object;
      },
    ),
    ShiftEntity: obx_int.EntityDefinition<ShiftEntity>(
      model: _entities[8],
      toOneRelations: (ShiftEntity object) => [],
      toManyRelations: (ShiftEntity object) => {},
      getId: (ShiftEntity object) => object.id,
      setId: (ShiftEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ShiftEntity object, fb.Builder fbb) {
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addFloat64(1, object.openingBalance);
        fbb.addInt64(2, object.status);
        fbb.addInt64(3, object.startedAt?.millisecondsSinceEpoch);
        fbb.addInt64(4, object.closedAt?.millisecondsSinceEpoch);
        fbb.addFloat64(5, object.closingBalance);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final startedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final closedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final openingBalanceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final statusParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final startedAtParam = startedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(startedAtValue);
        final closedAtParam = closedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(closedAtValue);
        final closingBalanceParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final object = ShiftEntity(
          id: idParam,
          openingBalance: openingBalanceParam,
          status: statusParam,
          startedAt: startedAtParam,
          closedAt: closedAtParam,
          closingBalance: closingBalanceParam,
        );

        return object;
      },
    ),
    CustomerEntity: obx_int.EntityDefinition<CustomerEntity>(
      model: _entities[9],
      toOneRelations: (CustomerEntity object) => [],
      toManyRelations: (CustomerEntity object) => {},
      getId: (CustomerEntity object) => object.id,
      setId: (CustomerEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CustomerEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final phoneOffset = fbb.writeString(object.phone);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, phoneOffset);
        fbb.addInt64(3, object.createdAt?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final createdAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final phoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final createdAtParam = createdAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
        final object = CustomerEntity(
          id: idParam,
          name: nameParam,
          phone: phoneParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CacheMetaEntity] entity fields to define ObjectBox queries.
class CacheMetaEntity_ {
  /// See [CacheMetaEntity.id].
  static final id = obx.QueryIntegerProperty<CacheMetaEntity>(
    _entities[0].properties[0],
  );

  /// See [CacheMetaEntity.boxName].
  static final boxName = obx.QueryStringProperty<CacheMetaEntity>(
    _entities[0].properties[1],
  );

  /// See [CacheMetaEntity.lastSyncedAt].
  static final lastSyncedAt = obx.QueryDateProperty<CacheMetaEntity>(
    _entities[0].properties[2],
  );
}

/// [HallTableEntity] entity fields to define ObjectBox queries.
class HallTableEntity_ {
  /// See [HallTableEntity.id].
  static final id = obx.QueryIntegerProperty<HallTableEntity>(
    _entities[1].properties[0],
  );

  /// See [HallTableEntity.number].
  static final number = obx.QueryIntegerProperty<HallTableEntity>(
    _entities[1].properties[1],
  );

  /// See [HallTableEntity.status].
  static final status = obx.QueryIntegerProperty<HallTableEntity>(
    _entities[1].properties[2],
  );

  /// See [HallTableEntity.drinkCount].
  static final drinkCount = obx.QueryIntegerProperty<HallTableEntity>(
    _entities[1].properties[3],
  );

  /// See [HallTableEntity.price].
  static final price = obx.QueryDoubleProperty<HallTableEntity>(
    _entities[1].properties[4],
  );

  /// See [HallTableEntity.customerName].
  static final customerName = obx.QueryStringProperty<HallTableEntity>(
    _entities[1].properties[5],
  );
}

/// [CategoryEntity] entity fields to define ObjectBox queries.
class CategoryEntity_ {
  /// See [CategoryEntity.id].
  static final id = obx.QueryIntegerProperty<CategoryEntity>(
    _entities[2].properties[0],
  );

  /// See [CategoryEntity.name].
  static final name = obx.QueryStringProperty<CategoryEntity>(
    _entities[2].properties[1],
  );

  /// See [CategoryEntity.imagePath].
  static final imagePath = obx.QueryStringProperty<CategoryEntity>(
    _entities[2].properties[2],
  );

  /// See [CategoryEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<CategoryEntity>(
    _entities[2].properties[3],
  );

  /// See [CategoryEntity.sortOrder].
  static final sortOrder = obx.QueryIntegerProperty<CategoryEntity>(
    _entities[2].properties[4],
  );

  /// See [CategoryEntity.nameEn].
  static final nameEn = obx.QueryStringProperty<CategoryEntity>(
    _entities[2].properties[5],
  );
}

/// [MenuItemEntity] entity fields to define ObjectBox queries.
class MenuItemEntity_ {
  /// See [MenuItemEntity.id].
  static final id = obx.QueryIntegerProperty<MenuItemEntity>(
    _entities[3].properties[0],
  );

  /// See [MenuItemEntity.categoryId].
  static final categoryId = obx.QueryIntegerProperty<MenuItemEntity>(
    _entities[3].properties[1],
  );

  /// See [MenuItemEntity.name].
  static final name = obx.QueryStringProperty<MenuItemEntity>(
    _entities[3].properties[2],
  );

  /// See [MenuItemEntity.price].
  static final price = obx.QueryDoubleProperty<MenuItemEntity>(
    _entities[3].properties[3],
  );

  /// See [MenuItemEntity.imagePath].
  static final imagePath = obx.QueryStringProperty<MenuItemEntity>(
    _entities[3].properties[4],
  );

  /// See [MenuItemEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<MenuItemEntity>(
    _entities[3].properties[5],
  );

  /// See [MenuItemEntity.sortOrder].
  static final sortOrder = obx.QueryIntegerProperty<MenuItemEntity>(
    _entities[3].properties[6],
  );

  /// See [MenuItemEntity.nameEn].
  static final nameEn = obx.QueryStringProperty<MenuItemEntity>(
    _entities[3].properties[7],
  );
}

/// [OrderEntity] entity fields to define ObjectBox queries.
class OrderEntity_ {
  /// See [OrderEntity.id].
  static final id = obx.QueryIntegerProperty<OrderEntity>(
    _entities[4].properties[0],
  );

  /// See [OrderEntity.tableId].
  static final tableId = obx.QueryIntegerProperty<OrderEntity>(
    _entities[4].properties[1],
  );

  /// See [OrderEntity.status].
  static final status = obx.QueryIntegerProperty<OrderEntity>(
    _entities[4].properties[2],
  );

  /// See [OrderEntity.customerName].
  static final customerName = obx.QueryStringProperty<OrderEntity>(
    _entities[4].properties[3],
  );

  /// See [OrderEntity.paidAmount].
  static final paidAmount = obx.QueryDoubleProperty<OrderEntity>(
    _entities[4].properties[4],
  );

  /// See [OrderEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<OrderEntity>(
    _entities[4].properties[5],
  );

  /// See [OrderEntity.closedAt].
  static final closedAt = obx.QueryDateProperty<OrderEntity>(
    _entities[4].properties[6],
  );

  /// See [OrderEntity.tableNumber].
  static final tableNumber = obx.QueryIntegerProperty<OrderEntity>(
    _entities[4].properties[7],
  );

  /// See [OrderEntity.paymentMethod].
  static final paymentMethod = obx.QueryIntegerProperty<OrderEntity>(
    _entities[4].properties[8],
  );

  /// See [OrderEntity.locationKind].
  static final locationKind = obx.QueryIntegerProperty<OrderEntity>(
    _entities[4].properties[9],
  );

  /// See [OrderEntity.customerId].
  static final customerId = obx.QueryIntegerProperty<OrderEntity>(
    _entities[4].properties[10],
  );

  /// See [OrderEntity.createdBy].
  static final createdBy = obx.QueryStringProperty<OrderEntity>(
    _entities[4].properties[11],
  );

  /// See [OrderEntity.cancelReason].
  static final cancelReason = obx.QueryStringProperty<OrderEntity>(
    _entities[4].properties[12],
  );
}

/// [OrderItemEntity] entity fields to define ObjectBox queries.
class OrderItemEntity_ {
  /// See [OrderItemEntity.id].
  static final id = obx.QueryIntegerProperty<OrderItemEntity>(
    _entities[5].properties[0],
  );

  /// See [OrderItemEntity.orderId].
  static final orderId = obx.QueryIntegerProperty<OrderItemEntity>(
    _entities[5].properties[1],
  );

  /// See [OrderItemEntity.menuItemId].
  static final menuItemId = obx.QueryIntegerProperty<OrderItemEntity>(
    _entities[5].properties[2],
  );

  /// See [OrderItemEntity.name].
  static final name = obx.QueryStringProperty<OrderItemEntity>(
    _entities[5].properties[3],
  );

  /// See [OrderItemEntity.price].
  static final price = obx.QueryDoubleProperty<OrderItemEntity>(
    _entities[5].properties[4],
  );

  /// See [OrderItemEntity.imagePath].
  static final imagePath = obx.QueryStringProperty<OrderItemEntity>(
    _entities[5].properties[5],
  );

  /// See [OrderItemEntity.quantity].
  static final quantity = obx.QueryIntegerProperty<OrderItemEntity>(
    _entities[5].properties[6],
  );

  /// See [OrderItemEntity.nameEn].
  static final nameEn = obx.QueryStringProperty<OrderItemEntity>(
    _entities[5].properties[7],
  );
}

/// [TreasuryTransactionEntity] entity fields to define ObjectBox queries.
class TreasuryTransactionEntity_ {
  /// See [TreasuryTransactionEntity.id].
  static final id = obx.QueryIntegerProperty<TreasuryTransactionEntity>(
    _entities[6].properties[0],
  );

  /// See [TreasuryTransactionEntity.title].
  static final title = obx.QueryStringProperty<TreasuryTransactionEntity>(
    _entities[6].properties[1],
  );

  /// See [TreasuryTransactionEntity.subtitle].
  static final subtitle = obx.QueryStringProperty<TreasuryTransactionEntity>(
    _entities[6].properties[2],
  );

  /// See [TreasuryTransactionEntity.amount].
  static final amount = obx.QueryDoubleProperty<TreasuryTransactionEntity>(
    _entities[6].properties[3],
  );

  /// See [TreasuryTransactionEntity.isIncome].
  static final isIncome = obx.QueryBooleanProperty<TreasuryTransactionEntity>(
    _entities[6].properties[4],
  );

  /// See [TreasuryTransactionEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<TreasuryTransactionEntity>(
    _entities[6].properties[5],
  );

  /// See [TreasuryTransactionEntity.createdBy].
  static final createdBy = obx.QueryStringProperty<TreasuryTransactionEntity>(
    _entities[6].properties[6],
  );

  /// See [TreasuryTransactionEntity.paymentMethod].
  static final paymentMethod =
      obx.QueryIntegerProperty<TreasuryTransactionEntity>(
        _entities[6].properties[7],
      );

  /// See [TreasuryTransactionEntity.orderId].
  static final orderId = obx.QueryIntegerProperty<TreasuryTransactionEntity>(
    _entities[6].properties[8],
  );
}

/// [MatchSeatEntity] entity fields to define ObjectBox queries.
class MatchSeatEntity_ {
  /// See [MatchSeatEntity.id].
  static final id = obx.QueryIntegerProperty<MatchSeatEntity>(
    _entities[7].properties[0],
  );

  /// See [MatchSeatEntity.number].
  static final number = obx.QueryIntegerProperty<MatchSeatEntity>(
    _entities[7].properties[1],
  );

  /// See [MatchSeatEntity.status].
  static final status = obx.QueryIntegerProperty<MatchSeatEntity>(
    _entities[7].properties[2],
  );

  /// See [MatchSeatEntity.drinkCount].
  static final drinkCount = obx.QueryIntegerProperty<MatchSeatEntity>(
    _entities[7].properties[3],
  );

  /// See [MatchSeatEntity.price].
  static final price = obx.QueryDoubleProperty<MatchSeatEntity>(
    _entities[7].properties[4],
  );

  /// See [MatchSeatEntity.customerName].
  static final customerName = obx.QueryStringProperty<MatchSeatEntity>(
    _entities[7].properties[5],
  );
}

/// [ShiftEntity] entity fields to define ObjectBox queries.
class ShiftEntity_ {
  /// See [ShiftEntity.id].
  static final id = obx.QueryIntegerProperty<ShiftEntity>(
    _entities[8].properties[0],
  );

  /// See [ShiftEntity.openingBalance].
  static final openingBalance = obx.QueryDoubleProperty<ShiftEntity>(
    _entities[8].properties[1],
  );

  /// See [ShiftEntity.status].
  static final status = obx.QueryIntegerProperty<ShiftEntity>(
    _entities[8].properties[2],
  );

  /// See [ShiftEntity.startedAt].
  static final startedAt = obx.QueryDateProperty<ShiftEntity>(
    _entities[8].properties[3],
  );

  /// See [ShiftEntity.closedAt].
  static final closedAt = obx.QueryDateProperty<ShiftEntity>(
    _entities[8].properties[4],
  );

  /// See [ShiftEntity.closingBalance].
  static final closingBalance = obx.QueryDoubleProperty<ShiftEntity>(
    _entities[8].properties[5],
  );
}

/// [CustomerEntity] entity fields to define ObjectBox queries.
class CustomerEntity_ {
  /// See [CustomerEntity.id].
  static final id = obx.QueryIntegerProperty<CustomerEntity>(
    _entities[9].properties[0],
  );

  /// See [CustomerEntity.name].
  static final name = obx.QueryStringProperty<CustomerEntity>(
    _entities[9].properties[1],
  );

  /// See [CustomerEntity.phone].
  static final phone = obx.QueryStringProperty<CustomerEntity>(
    _entities[9].properties[2],
  );

  /// See [CustomerEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<CustomerEntity>(
    _entities[9].properties[3],
  );
}
